import type { Metadata } from "next";
import { Inter } from "next/font/google";
import TodosList from "./TodosList";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Creating Youtube Next Js App",
  description: "Generated by Me",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <main className='flex'>
      <div className=''>
        <TodosList />
      </div>
      <div className='flex-1'>{children}</div>
    </main>
  );
}
