import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Practicing for NEXT JS!",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <header className=''>This is Header</header>
      <body className={inter.className}>{children}</body>
      <footer className=''>This is Header</footer>
    </html>
  );
}
